name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .
  
  my-second-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
      - name: add permission
        run: chmod -x ./ci/build-app.sh
      - name: Build
        run: ./ci/build-app.sh
    needs: my-job
  
  my-third-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
      - name: add permission
        run: chmod -x ./ci/build-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
    needs: my-job