name: hello-world
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Clone:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .
  
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
      - name: Build
        run: bash ci/build-app.sh
  
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
      - name: add permission
        run: chmod +x ./ci/unit-test-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
    needs: Clone

  Docker-image:
    runs-on: ubuntu-latest
    #container: gradle:6-jdk11
    needs:
      - Build
      - Test
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: .
      - name: build
        run: bash ./ci/build-docker.sh
      - name: push
        run: bash ci/push-docker.sh export GIT_COMMIT="GA-$GITHUB_SHA"